### PR TITLE
Requests to get Refresh Token

### PR DESCRIPTION
**Pull request by jotraverso**
### Requests to get Refresh Token

Added requests to obtain Authorization Code previous to get Access and Refresh tokens following the instructions found here
https://medium.com/@bpmmendis94/obtain-access-refresh-tokens-from-salesforce-rest-api-a324fe4ccd9b

- OAuth 1 - Get Authorization Code. Requests a URL to log in at Salesforce to get an authorization code.
The connected App Policies should be configured with Permitted Users = "All users may self-authorize"
You may use https://oauth.pstmn.io/v1/callback or https://www.getpostman.com/oauth2/callback as redirect url

- OAuth 2 - Post for Access and Refresh Token. Uses the authorization code to obtain an access token and a refresh token in the same call.

### CODE REVIEW

**Comment by scolladon** [comment]
Hi @jotraverso !

Thanks for your pull request.
I wonder if those calls correspond to already existing ones ? 
- OAuth 1 => Web Server Flow 1
- OAuth 2 => Web Server Flow 2

Seb

**Comment by jotraverso** [comment]
Hi @scolladon,

It's a good point :)

Let me suggest to set up the __refreshToken_ environment var in the test script of the Web Server Flow 2

pm.environment.set("_accessToken", jsonData.access_token);
**pm.environment.set("_refreshToken", jsonData.access_token);**
pm.environment.set("_endpoint", jsonData.instance_url);
pm.environment.set("_userId", id.pop());
pm.environment.set("_orgId", id.pop());

I cannot promise, but I'll try to submit a new pull request for this improvement, think you can close.

Jorge Ortega.

**Comment by scolladon** [comment]
That's a very good idea @jotraverso !

I think it could also be done in the User Agent Flow right ?

**Comment by scolladon** [comment]
duplicated by  #32

**Pull request closed without merging**
